permalink: /:year:month:day/:title
url: https://temporary.fun
baseurl: /

# variables
name: Write-Host "Welcome!^"
description: Apparently I needed a blog for things, so it's happening here and now


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true